[package]
name = "bard-client"
version = "0.1.0"
authors = ["msyfls123 <msyfls123@gmail.com>"]
description = "Built as wasm application with yew."
repository = "https://github.com/msyfls123/bard"
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.78"
web-sys = "0.3.55"
js-sys = "0.3.47"
yew = "0.19.3"
