[package]
name = "bard-server"
version = "0.1.0"
authors = ["msyfls123 <msyfls123@gmail.com>"]
description = "Built as binary application with Rocket."
repository = "https://github.com/msyfls123/bard"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
rocket = "0.5.0-rc.1"
