name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Rust cache
        uses: Swatinem/rust-cache@v1

      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Build static files
        run: ./script/build_client.sh

      - name: Build server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin server --release

      - name: Run
        run: ./script/run_on_ci.sh

      - name: Archive debug artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            target/release/server
            server/templates
            static/
            Rocket.toml
            !static/.gitignore
