name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Rust cache
        uses: Swatinem/rust-cache@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "16.7.0"

      - name: Install node modules
        run: npm i
        working-directory: ./client

      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Build static files
        run: ./script/build_client.sh

      - name: Build server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin server --release

      - name: Run
        run:
          chmod +x ./target/release/server
          ./script/run_on_ci.sh

      - name: Archive debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            target/release/server
            server/templates
            static/
            Rocket.toml
            DEPLOY.md
            Dockerfile
            docker-compose.yml
            !static/.gitignore
